global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "usuariosCRUD"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["usuarios-crud:8080"]

  - job_name: "suscripcionesCRUD"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "sucripciones-crud:8080" ]

  - job_name: "suscriptoresGET"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["suscriptores-get:8080"]

  - job_name: "PCSsuscriptores"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["pcs:8080"]

  - job_name: "MixbiUsuarioSuscripcion"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["mixbi:8080"]

  - job_name: "agregadorSuscripciones"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["agregador-suscripciones:8080"]
