server:
  port: 8080


spring:
  application:
    name: kafka-LowLevelConsumer
  kafka:
    bootstrap-servers: ${kafka:localhost}:29092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        key.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        value.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        schema.registry.url: http://${schema-registry:localhost}:8081
  datasource:
    url: jdbc:postgresql://suscriptores-get-db:5432/suscribers
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
