version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Instalar Maven
          command: sudo apt update && sudo apt install -y maven
      - run:
          name: Compilar el proyecto
          command: mvn clean package  # Compila y genera el JAR en `target/`
      - run:
          name: Verificar archivos en `target/`
          command: ls -l target/
      - run:
          name: Construir y levantar contenedores
          command: docker-compose up --build -d

  start_containers:
    steps:
      - checkout  # Clona el código
      - run:
          name: Verificar versión de Docker
          command: docker --version
      - run:
          name: Levantar los contenedores con Docker Compose
          command: docker-compose up --build -d

  run_dashboard:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Instalar dependencias de Python
          command: pip install -r dataPython/dashboard/requirements.txt
      - run:
          name: Ejecutar el dashboard.py
          command: python3 dataPython/dashboard/dashboard.py

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      - start_containers:
          requires:
            - build
      - run_dashboard:
          requires:
            - start_containers
