version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0  # Usa una imagen oficial de CircleCI con Java 11
    steps:
      - checkout
      - run:
          name: Instalar certificados y Java correctamente
          command: |
            apt-get update
            apt-get install -y ca-certificates-java
            update-ca-certificates
      - run:
          name: Instalar Maven
          command: sudo apt update && sudo apt install -y maven
      - run:
          name: Verificar versión de Java y Maven
          command: java -version && mvn -version
      - run:
          name: Compilar el proyecto
          command: mvn clean package
      - run:
          name: Verificar archivos en `target/`
          command: ls -l target/

  start_containers:
    machine: true  # Usa una máquina virtual con Docker preinstalado
    steps:
      - checkout
      - run:
          name: Verificar versión de Docker y Docker Compose
          command: docker --version && docker-compose --version
      - run:
          name: Levantar los contenedores con Docker Compose
          command: docker-compose up --build -d

  run_dashboard:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Instalar dependencias de Python
          command: |
            pip install --upgrade pip
            pip install -r dataPython/dashboard/requirements.txt
      - run:
          name: Ejecutar el dashboard.py
          command: python3 dataPython/dashboard/dashboard.py

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      - start_containers:
          requires:
            - build
      - run_dashboard:
          requires:
            - start_containers
