server:
  port: 8080

spring:
  application:
    name: enviador-alumnos
  kafka:
    bootstrap-servers: ${kafka:localhost}:29092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://${schema-registry:localhost}:8081

environment:
  alumno-topic: alumnos