server:
  port: 8080

spring:
  application:
    name: usuarios-crud
  kafka:
    bootstrap-servers: ${kafka:localhost}:29092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://${schema-registry:localhost}:8081
  datasource:
    url: jdbc:postgresql://usuarios-db:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


environment:
  user-topic: users
