server:
  port: 8080

spring:
  application:
    name: suscripciones-crud
  kafka:
    bootstrap-servers: ${kafka:localhost}:29092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://${schema-registry:localhost}:8081

management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: '*'
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

environment:
  user-topic: users