server:
  port: 8101

spring:
  application:
    name: suscripciones-crud
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://localhost:8081

environment:
  user-topic: users